"""criação do modelo de pedidos parcial

Revision ID: 1f8c749ebbba
Revises: cc5b04960f22
Create Date: 2024-10-31 13:12:31.951563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f8c749ebbba'
down_revision: Union[str, None] = 'cc5b04960f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    op.drop_table('produtos')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('produtos',
    sa.Column('codigo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('preco', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('data_de_validade', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('disponibilidade', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('codigo_de_barras', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('secao', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('estoque_inicial', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imagem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('codigo', name='produtos_pkey')
    )
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clientes_pkey')
    )
    # ### end Alembic commands ###
