"""pequena alteração no modelo de pedido(remoção da coluna secao dos produtos)em pedido model 

Revision ID: 5300552b09e7
Revises: 539f2438ae74
Create Date: 2024-11-03 15:32:56.697934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5300552b09e7'
down_revision: Union[str, None] = '539f2438ae74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
