"""pequena alteração no modelo de pedido(remoção da coluna cliente)em pedido model 

Revision ID: 539f2438ae74
Revises: 029169bec9c5
Create Date: 2024-11-03 15:30:01.278299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '539f2438ae74'
down_revision: Union[str, None] = '029169bec9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('users')
    op.drop_table('produtos')
    op.drop_table('clientes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('clientes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clientes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('produtos',
    sa.Column('codigo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('preco', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('data_de_validade', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('disponibilidade', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('codigo_de_barras', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('secao', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('estoque_inicial', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imagem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('codigo', name='produtos_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('pedidos',
    sa.Column('codigo_pedido', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('periodo', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status_pedido', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cliente', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('secao_dos_produts', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='pedidos_cliente_id_fkey'),
    sa.PrimaryKeyConstraint('codigo_pedido', name='pedidos_pkey')
    )
    # ### end Alembic commands ###
