"""Alterações no modelo ProdutoModel

Revision ID: cc5b04960f22
Revises: 290e8fba5455
Create Date: 2024-10-30 17:37:46.835269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5b04960f22'
down_revision: Union[str, None] = '290e8fba5455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
