"""segunda migração

Revision ID: fad8e3352640
Revises: 054315e0712f
Create Date: 2025-01-22 22:29:26.036742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fad8e3352640'
down_revision: Union[str, None] = '054315e0712f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    op.drop_table('pedidos')
    op.drop_table('users')
    op.drop_table('produtos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('codigo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('preco', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('data_de_validade', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('disponibilidade', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('codigo_de_barras', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('secao', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('estoque_inicial', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imagem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('codigo', name='produtos_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cargo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('pedidos',
    sa.Column('codigo_pedido', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('periodo', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status_pedido', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('secao_dos_produtos', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('id_do_cliente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_do_cliente'], ['clientes.id'], name='pedidos_id_do_cliente_fkey'),
    sa.PrimaryKeyConstraint('codigo_pedido', name='pedidos_pkey')
    )
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clientes_pkey')
    )
    # ### end Alembic commands ###
